#!/usr/bin/env python3
"""
run_pipeline_stage.py — Manually trigger a pipeline stage for a client

Usage:
    python scripts/run_pipeline_stage.py --stage transcript_parser --client summit_therapy
    python scripts/run_pipeline_stage.py --stage sitemap --client summit_therapy
    python scripts/run_pipeline_stage.py --stage content --client summit_therapy
    python scripts/run_pipeline_stage.py --stage sitemap --client summit_therapy --revision "Add a FAQs page"

Currently supported stages:
    transcript_parser   — Parse meeting transcript → structured Notion fields
    mood_board          — Generate mood board variation briefs (manual process)
    sitemap             — Generate sitemap page hierarchy
    content             — Generate full page copy for all sitemap pages

Client configs live in config/clients.json (auto-generated by make onboard).
"""
import argparse
import asyncio
import json
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from config.clients import CLIENTS
from src.config import settings
from src.integrations.clickup import ClickUpClient
from src.integrations.notion import NotionClient

# ── Stage runners ──────────────────────────────────────────────────────────────


async def run_sitemap(client_key: str, notion: NotionClient, clickup: ClickUpClient, revision_notes: str = "") -> dict:
    from src.agents.sitemap import SitemapAgent

    cfg = CLIENTS[client_key]
    agent = SitemapAgent(
        notion=notion,
        clickup=clickup,
        model=settings.anthropic_model,
        max_tokens=16000,
    )
    result = await agent.run(
        client_id=cfg["client_id"],
        client_info_db_id=cfg["client_info_db_id"],
        client_log_db_id=cfg.get("client_log_db_id", ""),
        brand_guidelines_db_id=cfg["brand_guidelines_db_id"],
        sitemap_db_id=cfg["sitemap_db_id"],
        business_profile_page_id=cfg.get("business_profile_page_id", ""),
        revision_notes=revision_notes,
    )

    # Interactive approval for Tier 3 suggestions
    suggestions = result.get("tier3_suggestions") or []
    if suggestions:
        approved = _prompt_for_tier3_approval(suggestions)
        if approved:
            sm_db = result.get("sitemap_db_id") or cfg["sitemap_db_id"]
            slug_to_id = result.get("slug_to_id") or {}
            written = await agent.write_approved_suggestions(approved, sm_db, slug_to_id)
            print(f"\n✓ Added {len(written)} Tier 3 page(s) to the sitemap as Draft.")
            result["tier3_approved_count"] = len(written)
            result["tier3_approved_ids"]   = written
            result["pages_created"]        = result.get("pages_created", 0) + len(written)
        else:
            print("\n→ No Tier 3 suggestions added. Baseline sitemap only.")
            result["tier3_approved_count"] = 0
    return result


def _prompt_for_tier3_approval(suggestions: list[dict]) -> list[dict]:
    """Show each Tier 3 suggestion and prompt y/n. Returns the approved subset."""
    print(f"\n{'='*70}")
    print(f"  Tier 3 Suggestions — {len(suggestions)} client-specific pages proposed")
    print(f"{'='*70}")
    print(f"\nFor each suggestion below: type 'y' to add it to the sitemap,")
    print(f"'n' to skip, 'a' to accept all remaining, or 's' to skip all remaining.\n")

    approved: list[dict] = []
    accept_all = False
    skip_all = False

    for i, page in enumerate(suggestions, 1):
        title = page.get("title", "(no title)")
        slug = page.get("slug", "(no slug)")
        section = page.get("section", "?")
        rationale = page.get("rationale", "")
        purpose = page.get("purpose", "")

        print(f"\n[{i}/{len(suggestions)}] {title}")
        print(f"      Section: {section}   Slug: {slug}")
        if rationale:
            print(f"      Why: {rationale}")
        if purpose:
            print(f"      Purpose: {purpose[:220]}")

        if accept_all:
            print(f"      → Auto-accepted")
            approved.append(page)
            continue
        if skip_all:
            print(f"      → Auto-skipped")
            continue

        while True:
            ans = input("      Add this page? [y/N/a/s]: ").strip().lower()
            if ans in ("", "n"):
                break
            elif ans == "y":
                approved.append(page)
                break
            elif ans == "a":
                approved.append(page)
                accept_all = True
                break
            elif ans == "s":
                skip_all = True
                break
            else:
                print("      (Answer with y, n, a, or s.)")

    print(f"\n{'='*70}")
    print(f"  Approved {len(approved)}/{len(suggestions)} Tier 3 pages.")
    print(f"{'='*70}")
    return approved


async def run_content(client_key: str, notion: NotionClient, clickup: ClickUpClient, revision_notes: str = "", **_) -> dict:
    from src.agents.content import ContentAgent

    cfg = CLIENTS[client_key]
    agent = ContentAgent(
        notion=notion,
        clickup=clickup,
        model=settings.anthropic_model,
        max_tokens=16000,
    )
    return await agent.run(
        client_id=cfg["client_id"],
        client_info_db_id=cfg["client_info_db_id"],
        client_log_db_id=cfg.get("client_log_db_id", ""),
        brand_guidelines_db_id=cfg["brand_guidelines_db_id"],
        sitemap_db_id=cfg["sitemap_db_id"],
        business_profile_page_id=cfg.get("business_profile_page_id", ""),
        content_db_id=cfg.get("content_db_id", ""),
        revision_notes=revision_notes,
    )


STAGE_RUNNERS = {
    "sitemap": run_sitemap,
    "content": run_content,
}


# ── Main ───────────────────────────────────────────────────────────────────────

async def main(stage: str, client_key: str, revision_notes: str = "") -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )

    if client_key not in CLIENTS:
        print(f"ERROR: Unknown client '{client_key}'. Available: {list(CLIENTS.keys())}")
        sys.exit(1)

    if stage not in STAGE_RUNNERS:
        print(f"ERROR: Unknown stage '{stage}'. Available: {list(STAGE_RUNNERS.keys())}")
        sys.exit(1)

    print(f"\nRunning stage: {stage} | client: {client_key}")
    if revision_notes:
        print(f"Revision notes: {revision_notes[:80]}{'...' if len(revision_notes) > 80 else ''}")
    print("=" * 60)

    notion = NotionClient(settings.notion_api_key)
    clickup = ClickUpClient(settings.clickup_api_key, settings.clickup_workspace_id or "")

    runner = STAGE_RUNNERS[stage]
    result = await runner(client_key, notion, clickup, revision_notes=revision_notes)

    print("\n" + "=" * 60)
    print("RESULT:")
    print(json.dumps(result, indent=2, default=str))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run a pipeline stage for a client")
    parser.add_argument(
        "--stage", required=True, choices=list(STAGE_RUNNERS.keys()),
        help="Pipeline stage to run"
    )
    parser.add_argument("--client", required=True, default="wellwell")
    parser.add_argument("--revision", default="", metavar="NOTES",
                        help="Feedback from previous run to guide regeneration")
    args = parser.parse_args()

    asyncio.run(main(args.stage, args.client, revision_notes=args.revision))
