"""
config/clients.py — Central client registry

Two sources merged into CLIENTS:

  1. _MANUAL (below) — existing clients, managed by hand.
     WellWell lives here permanently.

  2. config/clients.json — auto-generated by the onboarding agent.
     Every new client onboarded via `make onboard` lands here automatically.
     Never edit clients.json by hand.

To add a client manually, copy the template block below into _MANUAL.
To add via the automated flow, run: make onboard

Usage in scripts:
    from config.clients import CLIENTS
    cfg = CLIENTS["wellwell"]
"""
import json
from pathlib import Path

_MANUAL: dict[str, dict] = {
    "wellwell": {
        # ── Identity ───────────────────────────────────────────────────────────
        "client_id":   "wellwell",
        "name":        "WellWell",

        # ── Notion database IDs ────────────────────────────────────────────────
        # Generated by: python scripts/setup_notion.py --client-name "WellWell" ...
        "client_info_db_id":       "79c6a439-f369-4a47-af1a-89645fef6f4f",
        "meeting_notes_db_id":     "6eedcfe8-bcd7-4de2-837c-8fb79fdce249",
        "brand_guidelines_db_id":  "b7604d57-de3f-455a-a54c-acf3d41fb276",
        "mood_board_db_id":        "b2eb103b-a45e-490f-9521-1914780e5fdb",
        "sitemap_db_id":           "d70fe7ab-a5f4-4814-9209-4bb6eb05b21a",
        "content_db_id":           "330f7f45-333e-81fc-b84f-c92f533cdafd",
        "wireframes_db_id":        "b0375b40-60e7-49e3-9137-588c36794b5b",
        "hifi_db_id":              "2d6af757-40ac-4f67-ae16-ee91574d9ad8",
        "action_items_db_id":      "109f1a05-4f62-4b0b-aa1b-284f7eb7e619",
        "images_db_id":            "334f7f45-333e-81a6-b3f5-f53c21094085",

        # ── Specific entry IDs ────────────────────────────────────────────────
        "meeting_notes_entry_id":  "32ff7f45-333e-812b-9c7b-f35e11923393",

        # ── ClickUp ───────────────────────────────────────────────────────────
        # RxMedia Clients space → WellWell folder → Website Development list
        "clickup_review_list_id":  "901816474808",
    },

    # ── Template for new clients ───────────────────────────────────────────────
    # "new_client": {
    #     "client_id":   "new_client",
    #     "name":        "Client Name",
    #     "client_info_db_id":       "",
    #     "meeting_notes_db_id":     "",
    #     "brand_guidelines_db_id":  "",
    #     "mood_board_db_id":        "",
    #     "sitemap_db_id":           "",
    #     "content_db_id":           "",
    #     "wireframes_db_id":        "",
    #     "hifi_db_id":              "",
    #     "action_items_db_id":      "",
    #     "images_db_id":            "",
    #     "meeting_notes_entry_id":  "",
    #     "clickup_review_list_id":  "",
    # },
}

# ── Auto-generated clients (written by onboarding agent) ──────────────────────
_JSON_PATH = Path(__file__).parent / "clients.json"
_AUTO: dict[str, dict] = {}
if _JSON_PATH.exists():
    try:
        _AUTO = json.loads(_JSON_PATH.read_text()) or {}
    except (json.JSONDecodeError, OSError):
        _AUTO = {}

# Merge: manual entries take precedence over auto-generated ones
CLIENTS: dict[str, dict] = {**_AUTO, **_MANUAL}
