"""
config/clients.py — Central client registry

Two sources merged into CLIENTS:

  1. _MANUAL (below) — existing clients managed by hand.
     Use this for any client that needs a manual override or was set up
     before the automated onboarding flow existed.

  2. config/clients.json — auto-generated by the onboarding agent.
     Every new client onboarded via `make onboard` lands here automatically.
     Never edit clients.json by hand.

To add a client manually, copy the template block below into _MANUAL.
To add via the automated flow, run: make onboard

Usage in scripts:
    from config.clients import CLIENTS
    cfg = CLIENTS["summit_therapy"]
"""
import json
from pathlib import Path

_MANUAL: dict[str, dict] = {
    # ── Template for new clients ───────────────────────────────────────────────
    # "new_client": {
    #     "client_id":   "new_client",
    #     "name":        "Client Name",
    #
    #     # ── Active services ───────────────────────────────────────────────────
    #     # List only what this client is paying for. Scripts + Rex read this
    #     # to know what pipelines apply. Rex answers "what services is X on?"
    #     #
    #     # Available service keys:
    #     #   website_build     — full pipeline: sitemap → content → images → Webflow
    #     #   care_plan         — monthly PageSpeed + ADA report
    #     #   seo               — keyword research, competitor analysis, battle plan
    #     #   gbp_management    — GBP posts + review responses
    #     #   blog              — blog ideas → write → publish
    #     #   social_media      — Instagram/Facebook + LinkedIn posts
    #     #   newsletter        — monthly email newsletter (future)
    #     #   paid_ads          — paid ads management (future)
    #     "services": {
    #         "website_build":   False,
    #         "care_plan":       False,
    #         "seo":             False,
    #         "gbp_management":  False,
    #         "blog":            False,
    #         "blog_posts_per_month": 0,   # 1–12; ignored if blog is False
    #         "social_media":    False,
    #         "newsletter":      False,
    #         "paid_ads":        False,
    #     },
    #
    #     # ── Notion DB IDs ─────────────────────────────────────────────────────
    #     "client_info_db_id":       "",
    #     "meeting_notes_db_id":     "",
    #     "brand_guidelines_db_id":  "",
    #     "mood_board_db_id":        "",
    #     "sitemap_db_id":           "",
    #     "content_db_id":           "",
    #     "wireframes_db_id":        "",
    #     "hifi_db_id":              "",
    #     "action_items_db_id":      "",
    #     "images_db_id":            "",
    #     "care_plan_db_id":         "",
    #     # ── SEO (if seo in services) ──────────────────────────────────────────
    #     "competitors_db_id":       "",
    #     "keywords_db_id":          "",
    #     "seo_metrics_db_id":       "",
    #     "gbp_posts_db_id":         "",  # auto-created on first make gbp-posts run
    #     # ── Blog (if blog in services) ────────────────────────────────────────
    #     "blog_posts_db_id":        "",  # auto-created on first make blog-ideas run
    #     "blog_voice_setup_page_id":"",  # set by make blog-setup
    #     # ── Social (if social_media in services) ──────────────────────────────
    #     "social_posts_db_id":      "",  # auto-created on first make social-posts run
    #     # ── SEO Reporting (required for seo-report) ───────────────────────────
    #     "gbp_location_id":         "",  # GBP location ID (e.g. "locations/1234567890")
    #     "gsc_site_url":            "",  # exact URL in Search Console (e.g. "https://example.com/")
    #     "ga4_property_id":         "",  # numeric GA4 property ID (e.g. "123456789")
    #     "search_atlas_project_id": "",  # rank tracker project ID (optional)
    #     # ── Pipeline ──────────────────────────────────────────────────────────
    #     "meeting_notes_entry_id":  "",
    #     "clickup_review_list_id":  "",
    #     # ── Cross-client linking (blog) ───────────────────────────────────────
    #     "vertical":                "",  # e.g. "speech_pathology", "addiction_treatment"
    # },
}

# ── Auto-generated clients (written by onboarding agent) ──────────────────────
_JSON_PATH = Path(__file__).parent / "clients.json"
_AUTO: dict[str, dict] = {}
if _JSON_PATH.exists():
    try:
        _AUTO = json.loads(_JSON_PATH.read_text()) or {}
    except (json.JSONDecodeError, OSError):
        _AUTO = {}

# Merge: manual entries take precedence over auto-generated ones
CLIENTS: dict[str, dict] = {**_AUTO, **_MANUAL}
