#!/usr/bin/env python3
"""
rebuild_sitemap.py — Clear and recreate the Sitemap DB from a definitive page list.

Used when the sitemap needs to be set from a known-correct list rather than
regenerated by Claude. Trashes all existing Draft pages, then creates the
correct set fresh.

Usage:
    python scripts/rebuild_sitemap.py --client summit_therapy
"""
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from config.clients import CLIENTS
from src.config import settings
from src.integrations.notion import NotionClient

# ── Definitive Summit Therapy sitemap ─────────────────────────────────────────
# Format: (title, slug, page_type, content_mode, section, order, purpose, nav_location)
SUMMIT_THERAPY_PAGES = [
    # ── Core ──────────────────────────────────────────────────────────────────
    ("Home", "/", "Static", "AI Generated", "Core", 1,
     "Primary entry point — introduce Summit Therapy, drive appointment requests, and showcase key services across speech, OT, and PT.",
     "Main Nav"),
    ("About Us", "/about", "Static", "AI Generated", "Core", 2,
     "Build trust through brand story, owner background (SLP + parent), local ownership, and clinic philosophy.",
     "Main Nav"),
    ("Our Team", "/about/team", "CMS", "Client Provided", "Core", 3,
     "CMS item — showcase therapist bios, credentials (CCCs, certifications), and specialties to build credibility.",
     "Main Nav"),
    ("Contact Us", "/contact", "Static", "AI Generated", "Core", 4,
     "Primary conversion page — appointment request form, two location addresses, phone, hours, and map.",
     "Main Nav"),

    # ── Who We Serve ──────────────────────────────────────────────────────────
    ("Who We Serve — Children", "/who-we-serve/children", "Static", "AI Generated", "Who We Serve", 10,
     "Gateway page for pediatric patients/families — curated view of services for infants and children with CTAs to relevant service pages.",
     "Main Nav"),
    ("Who We Serve — Adults", "/who-we-serve/adults", "Static", "AI Generated", "Who We Serve", 11,
     "Gateway page for adult patients and their families — curated view of services for adults with CTAs to relevant service pages.",
     "Main Nav"),

    # ── Services (Hubs) ───────────────────────────────────────────────────────
    ("Speech Therapy", "/services/speech-therapy", "Static", "AI Generated", "Services", 20,
     "Hub page for all speech therapy services — overview of conditions treated, approach, and links to subcategory pages.",
     "Main Nav"),
    ("Occupational Therapy", "/services/occupational-therapy", "Static", "AI Generated", "Services", 21,
     "Hub page for all OT services — overview, what to expect, and links to subcategory pages.",
     "Main Nav"),
    ("Physical Therapy", "/services/physical-therapy", "Static", "AI Generated", "Services", 22,
     "Coming soon hub page for PT services — introduces PT offering, captures interest, and outlines future subcategory pages for SEO indexing.",
     "Main Nav"),

    # ── Speech Therapy Subcategories (CMS collection: Service Subcategories) ──
    ("Sounds & Speech (Articulation)", "/services/speech-therapy/articulation", "CMS", "AI Generated", "Service Subcategories", 30,
     "CMS item — target patients with articulation disorders; explain condition, treatment approach, and outcomes. Parent service: Speech Therapy.",
     "Main Nav"),
    ("Fluency", "/services/speech-therapy/fluency", "CMS", "AI Generated", "Service Subcategories", 31,
     "CMS item — target patients with stuttering and fluency disorders; explain therapy approach and expected outcomes. Parent service: Speech Therapy.",
     "Main Nav"),
    ("Reading Comprehension", "/services/speech-therapy/reading-comprehension", "CMS", "AI Generated", "Service Subcategories", 32,
     "CMS item — target patients with reading and language comprehension challenges; explain how speech therapy addresses literacy. Parent service: Speech Therapy.",
     "Main Nav"),
    ("AAC (Augmentative & Alternative Communication)", "/services/speech-therapy/aac", "CMS", "AI Generated", "Service Subcategories", 33,
     "CMS item — target patients who use or need AAC devices; explain device types, therapy process, and outcomes. Parent service: Speech Therapy.",
     "Main Nav"),
    ("Speech Delay", "/services/speech-therapy/speech-delay", "CMS", "AI Generated", "Service Subcategories", 34,
     "CMS item — target parents of children with speech delay; explain early intervention, signs, and treatment approach. Parent service: Speech Therapy.",
     "Main Nav"),
    ("Aphasia", "/services/speech-therapy/aphasia", "CMS", "AI Generated", "Service Subcategories", 35,
     "CMS item — target adult patients and families dealing with aphasia post-stroke or brain injury; explain recovery approach. Parent service: Speech Therapy.",
     "Main Nav"),
    ("Parkinson's Disease", "/services/speech-therapy/parkinsons-disease", "CMS", "AI Generated", "Service Subcategories", 36,
     "CMS item — target patients with Parkinson's-related speech difficulties; explain LSVT LOUD and other approaches. Parent service: Speech Therapy.",
     "Main Nav"),
    ("Language Delay", "/services/speech-therapy/language-delay", "CMS", "AI Generated", "Service Subcategories", 37,
     "CMS item — target parents of children with language delay; explain assessment, early intervention, and expected progress. Parent service: Speech Therapy.",
     "Main Nav"),
    ("Second & Third Language Acquisition", "/services/speech-therapy/language-acquisition", "CMS", "AI Generated", "Service Subcategories", 38,
     "CMS item — target multilingual families; explain how speech therapy supports bilingual/multilingual language development. Parent service: Speech Therapy.",
     "Main Nav"),
    ("Feeding Therapy (Speech)", "/services/speech-therapy/feeding-therapy", "CMS", "AI Generated", "Service Subcategories", 39,
     "CMS item — target patients with feeding and swallowing disorders; explain evaluation process and therapy techniques. Parent service: Speech Therapy.",
     "Main Nav"),

    # ── OT Subcategories (CMS collection: Service Subcategories) ─────────────
    ("Fine Motor Skills", "/services/occupational-therapy/fine-motor-skills", "CMS", "AI Generated", "Service Subcategories", 50,
     "CMS item — target patients needing fine motor development; explain handwriting, grip, and dexterity therapy approaches. Parent service: Occupational Therapy.",
     "Main Nav"),
    ("Sensory Regulation", "/services/occupational-therapy/sensory-regulation", "CMS", "AI Generated", "Service Subcategories", 51,
     "CMS item — target patients with sensory processing challenges; explain sensory integration therapy and expected outcomes. Parent service: Occupational Therapy.",
     "Main Nav"),
    ("Feeding (OT)", "/services/occupational-therapy/feeding", "CMS", "AI Generated", "Service Subcategories", 52,
     "CMS item — target patients with feeding challenges from a sensory/motor perspective; explain OT's role in feeding therapy. Parent service: Occupational Therapy.",
     "Main Nav"),
    ("Activities of Daily Living", "/services/occupational-therapy/activities-of-daily-living", "CMS", "AI Generated", "Service Subcategories", 53,
     "CMS item — target patients needing help with ADLs; explain how OT restores independence in dressing, hygiene, and daily tasks. Parent service: Occupational Therapy.",
     "Main Nav"),
    ("Balance Coordination", "/services/occupational-therapy/balance-coordination", "CMS", "AI Generated", "Service Subcategories", 54,
     "CMS item — target patients with balance and coordination challenges; explain OT's role in improving motor coordination. Parent service: Occupational Therapy.",
     "Main Nav"),

    # ── PT Subcategories — Coming Soon (CMS collection: Service Subcategories)
    ("Gross Motor Skills", "/services/physical-therapy/gross-motor-skills", "CMS", "AI Generated", "Service Subcategories", 60,
     "CMS item (coming soon) — target patients with gross motor delays; establishes SEO presence before PT provider is hired. Parent service: Physical Therapy.",
     "Main Nav"),
    ("Walking & Balance", "/services/physical-therapy/walking-balance", "CMS", "AI Generated", "Service Subcategories", 61,
     "CMS item (coming soon) — target patients with gait and balance challenges; establishes SEO presence for future PT services. Parent service: Physical Therapy.",
     "Main Nav"),
    ("Infant Torticollis", "/services/physical-therapy/infant-torticollis", "CMS", "AI Generated", "Service Subcategories", 62,
     "CMS item (coming soon) — target parents of infants with torticollis; establishes SEO presence for future PT services. Parent service: Physical Therapy.",
     "Main Nav"),

    # ── Locations ─────────────────────────────────────────────────────────────
    ("Locations", "/locations", "Static", "AI Generated", "Locations", 70,
     "Overview of both clinic locations with address, hours, and directions — helps local SEO and patient wayfinding.",
     "Footer"),
    ("Frisco Clinic", "/locations/frisco", "CMS", "AI Generated", "Locations", 71,
     "CMS item — dedicated location page for the Frisco clinic; address, hours, parking, services offered, local SEO keywords.",
     "Footer"),
    ("McKinney Clinic", "/locations/mckinney", "CMS", "AI Generated", "Locations", 72,
     "CMS item — dedicated location page for the McKinney clinic; address, hours, parking, services offered, local SEO keywords.",
     "Footer"),

    # ── Patient Resources ─────────────────────────────────────────────────────
    ("Insurance & Billing", "/insurance", "Static", "Client Provided", "Patient Resources", 80,
     "Explain accepted insurance, self-pay rates, and billing process — reduces intake friction and support calls.",
     "Main Nav"),
    ("New Patient Resources", "/new-patients", "Static", "AI Generated", "Patient Resources", 81,
     "Guide new patients through what to expect — first visit, intake forms, how to prepare, FAQ.",
     "Main Nav"),

    # ── Blog ──────────────────────────────────────────────────────────────────
    ("Blog", "/blog", "CMS", "AI Generated", "Blog", 90,
     "Educational content hub — patient education articles, therapy tips, and local community content for SEO.",
     "Main Nav"),
    ("Blog Post — [Title]", "/blog/[post-slug]", "CMS", "AI Generated", "Blog", 91,
     "Individual blog post template — CMS-driven, supports categories, author, date, and related posts.",
     "Main Nav"),

    # ── Legal ─────────────────────────────────────────────────────────────────
    ("Privacy Policy", "/privacy-policy", "Static", "Client Provided", "Legal", 100,
     "HIPAA-compliant privacy policy covering patient data, cookies, and third-party services.",
     "Footer"),
    ("Terms of Service", "/terms", "Static", "Client Provided", "Legal", 101,
     "Terms governing use of the website and services.",
     "Footer"),
    ("Accessibility Statement", "/accessibility", "Static", "AI Generated", "Legal", 102,
     "ADA compliance statement — WCAG 2.1 conformance level and contact for accessibility issues.",
     "Footer"),
]


def _get_select(prop: dict) -> str:
    sel = prop.get("select")
    return sel.get("name", "") if sel else ""


async def main(client_key: str) -> None:
    cfg = CLIENTS[client_key]
    sitemap_db_id = cfg["sitemap_db_id"]
    notion = NotionClient(settings.notion_api_key)

    # ── Step 1: Add Nav Location field to DB (idempotent) ─────────────────────
    print("Ensuring Nav Location field exists on Sitemap DB...")
    await notion._client.request(
        path=f"databases/{sitemap_db_id}",
        method="PATCH",
        body={
            "properties": {
                "Nav Location": {
                    "select": {
                        "options": [
                            {"name": "Main Nav", "color": "blue"},
                            {"name": "Footer", "color": "gray"},
                        ]
                    }
                }
            }
        },
    )
    print("  ✓ Nav Location field ready")

    # ── Step 2: Trash all existing Draft pages ────────────────────────────────
    print("Fetching existing sitemap pages...")
    existing = await notion.query_database(sitemap_db_id)
    drafts = [e for e in existing if _get_select(e["properties"].get("Status", {})) == "Draft"]
    print(f"  Trashing {len(drafts)} Draft pages...")
    for page in drafts:
        await notion._client.request(
            path=f"pages/{page['id']}", method="PATCH", body={"in_trash": True}
        )
    print("  ✓ Cleared")

    # ── Step 3: Create all pages from definitive list ─────────────────────────
    print(f"\nCreating {len(SUMMIT_THERAPY_PAGES)} pages...")
    created = 0
    for title, slug, page_type, content_mode, section, order, purpose, nav_location in SUMMIT_THERAPY_PAGES:
        props = {
            "Page Title": {"title": [{"type": "text", "text": {"content": title}}]},
            "Slug": {"rich_text": [{"type": "text", "text": {"content": slug}}]},
            "Page Type": {"select": {"name": page_type}},
            "Content Mode": {"select": {"name": content_mode}},
            "Section": {"select": {"name": section}},
            "Nav Location": {"select": {"name": nav_location}},
            "Status": {"select": {"name": "Draft"}},
            "Order": {"number": order},
            "Purpose": {"rich_text": [{"type": "text", "text": {"content": purpose[:2000]}}]},
        }
        await notion._client.request(
            path="pages", method="POST",
            body={"parent": {"database_id": sitemap_db_id}, "properties": props},
        )
        print(f"  ✓ [{nav_location}] [{section}] {title}")
        created += 1

    print(f"\nDone — {created} pages created.")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--client", default="summit_therapy")
    args = parser.parse_args()
    asyncio.run(main(args.client))
